### ISSUE TITLE
helper.mk broken on MacOS and FreeBSD

### ISSUE THREAD

**Issue by kiwichris** [Xilinx/u-boot-xlnx#1]
The following fails on FreeBSD and MacOS ...

$ arm-rtems4.11-objdump -h  board/xilinx/zynq/libzynq.o | sed -e '/.*\.u_boot_list[^ ]\+/ ! {d;n}'
sed: 1: "/.*\.u_boot_list[^ ]\+/ ...": extra characters at the end of n command

The actual error in the build is ...

sed: 1: "/.*\.u_boot_list[^ ]\+/ ...": extra characters at the end of n command
sed: 1: "/@$/ { s/\(.*\)@$/*(SOR ...": bad flag in substitute command: '}'

I cannot see this file in the upstream u-boot repo. My sed is not up to a solution.

**Comment by michalsimek** [comment]
Please fix this in mainline. 

Thanks,
Michal
