### ISSUE TITLE
drivers/block/systemace.c endianness check not required

### ISSUE THREAD

**Issue by slugonamission** [Xilinx/u-boot-xlnx#17]
/drivers/block/systemace.c contains a check for byte ordering when writing to the peripheral on lines 48 and 62. Because of this check, the ace_writew and ace_readw functions fail on little-endian platforms.

From what I can gather, the SystemACE peripheral always expects data to to be written to it in little-endian order (I'm running off of DS080), hence no conditional is required in this case. I can submit a patch, but I currently don't have time to exhaustively test this change under all configurations.

**Comment by michalsimek** [comment]
Sysace can be changed to use endian detection. Sysace is pretty old IP and probably won't be changed to DM. Please reopen this if this is still problem.
