### ISSUE TITLE
zynq qspi and spi drivers cannot be configured simultaneously

### ISSUE THREAD

**Issue by khays-biamp** [Xilinx/u-boot-xlnx#19]
The hardware doesn't preclude using the zynq spi and qspi hardware simultaneously, but the drivers provided in zynq_qspi.c and zynq_spi.c have namespace conflicts, so they cannot be both configured simultaneously in U-Boot.

To recreate:

     #define CONFIG_ZYNQ_QSPI
     #define CONFIG_ZYNQ_SPI

in the same configuration header file, then build.

None of the example configurations do this, of course, so the problem won't be seen until a third-party designs a board that uses both SPI and QSPI interfaces.

**Comment by michalsimek** [comment]
Fixed by DM adoption.
