### ISSUE TITLE
Fixed clock rate in drivers/spi/zynq_spi.c

### ISSUE THREAD

**Issue by khays-biamp** [Xilinx/u-boot-xlnx#20]
inside of spi_setup_slave(), around line 155, appears:

	zslave->input_hz = 166666700;

This will give you obscure grief if you are using this driver with the SPI reference clock set to something other than 166.67MHz.  In particular, using a 200MHz clock results in derived clock rates that are too high for very slow devices (like a serial eeprom).

I realize this driver is probably being re-written, but in the mean time, this quick note might save someone else some trouble.

**Comment by sivadur** [comment]
This is now modified to use it from device tree and hence this no longer a valid issue

**Comment by khays-biamp** [comment]
I question the solution to this problem, as u-boot was not previously tied to requiring a device tree, in my understanding.

In our environment, we use multiple device trees, and have multiple dtbs available to u-boot, depending on the “personality” of the hardware, as determined by u-boot at runtime by reading a spi-connected EEPROM.

Your solution requires that I provide a “stub” dtb, just so I can get to the EEPROM.

This seems inelegant, as the spi clock rate can be derived from registers loaded via the RBL, or, more simply, setup as a CONFIG_ macro.

Kirk Hays •  Embedded Software Engineer
Biamp Systems  •  9300 SW Gemini Drive, Beaverton, OR 97008
www.biamp.com<http://www.biamp.com/>  •  tel. +1.503.641.9192  •  fax +1.503.626.0281

**Comment by michalsimek** [comment]
ok. DT is used right now but there is also an option to create some sort of platform data directly in u-boot to handle your case. How does that DT handling look like now? I think this will require more thinking how this should be done. Are you using FSBL or U-Boot SPL as primary bootloader? 
Handling stuff via DT has one big advantage which is that if you do EEPROM reading from first stage bootloader that you can directly pass correct DTB to the u-boot which does initializastion. 
But really this has to fit to your exact case and I don't have enough information right now how that configuration looks like.

Thanks,
Michal

**Comment by khays-biamp** [comment]
What we currently do, at board manufacture, is flash the device SKU into a very small SPI EEPROM (128 bytes), along with other data, like MAC addresses, date of manufacture, etc.

We generate a combined RBL/SPL image that is resident in the QSPI NOR.  The RBL sets up a “base” configuration suitable for running the SPL, which is loaded by the normal ZYNQ procedure into the OCM from the NOR.

The SPL continues HW init, loads U-Boot from the QSPI NOR, then hands control off to U-Boot.

U-boot, in our customization code, will read from the SPI EEPROM to get the product sku, then loads the appropriate DTB (one of n) from NOR, adorns it with additional product-specific or environment-specific key-value pairs, completes any product-specific HW initialization, and hands off to Linux.

I’m not saying your solution is wrong, it just seems to *assume* that a DTB would be available to U-Boot, which assumption was not previously present.  That would not necessarily constrain our implementation, but others more constrained on storage space might find it an issue.

FTR, we wound up writing our own SPI driver, as we needed the default QSPI driver, and, as noted in issue #19, they could not previously co-exist.

Kirk Hays •  Embedded Software Engineer
Biamp Systems  •  9300 SW Gemini Drive, Beaverton, OR 97008
www.biamp.com<http://www.biamp.com/>  •  tel. +1.503.641.9192  •  fax +1.503.626.0281

**Comment by michalsimek** [comment]
In past they could coexists but there was necessary to do one changes in the code. U-Boot is moving to DM which is bringing up DTB initialization. Also SPL in mainline is DTB driven now. 
Can you send me your customization code to see what you exactly are doing there <michals@xilinx.com>? I still think that the best option for you is to add board specific hook to generic SPL code which will contain this code. 

Thanks,
Michal

**Comment by khays-biamp** [comment]
If the mainline is moving that way, that’s good enough for me.  We’ll adapt at the appropriate time.

Thanks for considering my thoughts on the matter.

Kirk Hays •  Embedded Software Engineer
Biamp Systems  •  9300 SW Gemini Drive, Beaverton, OR 97008
www.biamp.com<http://www.biamp.com/>  •  tel. +1.503.641.9192  •  fax +1.503.626.0281

**Comment by michalsimek** [comment]
No problem. 

Thanks,
Michal
