### ISSUE TITLE
Adding Kintex 7 support to U-Boot

### ISSUE THREAD

**Issue by ajf58** [Xilinx/u-boot-xlnx#21]
Is there a plan to add support for Kintex 7 devices to Xilinx's U-Boot? There are definitions for Virtex 2 and Spartan 3 devices, but nothing following that.

**Comment by michalsimek** [comment]
Hi,
I am not running any ancient fpgas that's why I can't test these changes. But definitely unification is good to do always that's why patches are welcome.

Thanks,
Michal
