### ISSUE TITLE
Error in sdhci.c driver when running Zynq processor frequency about 783 MHz

### ISSUE THREAD

**Issue by bfroute-goog** [Xilinx/u-boot-xlnx#26]
I have discovered an apparent bug in the sdhci_send_command in drivers/mmc/sdhci.c.  When running a minimal u-boot configuration and having the processor speed greater than about 785 MHz, the sdhci driver has a retry loop in sdhci_send_command that doesn't wait long enough.  The current implementation just uses a decrementing counter.  If the processor's frequency is high enough, there is a case where the retry loop completes too early.   I suggest the retry loop use udelay or equivalent to accommodate the case where the processor frequency is too high.

The result error was that "mmc info" could not properly instantiate, interrogate, and setup the SD card when the processor's CPU (ARM) frequency was too high.

**Comment by michalsimek** [comment]
It should be time based on timer. Solution based on get_timer() is correct. Please send the fix to mainline instead of SoC vendor tree. 

Thanks,
Michal
