### ISSUE TITLE
Relationship of u-boot-xlnx to git.denx.de?

### ISSUE THREAD

**Issue by konrad-schwarz** [Xilinx/u-boot-xlnx#28]
What is the preferred repository for U-Boot on Xilinx hardware, especially Zynq?

**Comment by michalsimek** [comment]
denx.de is mainline/upstream U-Boot version. u-boot-xlnx is SoC vendor tree which is having the latest & greatest features provided by SoC vendor. Also this repository is used by PetaLinux. If I want to have more features and there is no problem that they are not in mainline I would use u-boot-xlnx. If I prefer to use well reviewed version and set of features in mainline is sufficient for me, then I would use mainline version. 
Also feel free to diff both trees and you will find out that there is no big diff. Only SPI and Nand drivers are missing plus some minor things.
