### ISSUE TITLE
Zynq QSPI (Dual Parallel Mode) - U-boot does NOT read the Flag Status Register from 2nd Chip

### ISSUE THREAD

**Issue by senthil1179** [Xilinx/u-boot-xlnx#3]
Context
---------------------------
U-Boot 13.4
HW - Zynq7000 
        - N25q_512mb  
        - Dual Parallel Mode 
        - Full memory capacity is 128 Mega Bytes

Question
---------------------------
Is there a way to read back the FLAG STATUS REGISTERS from both the Chips ?  Ideally the Chip Select should be de-asserted only after both chips are done with Erase operation. But the Driver reads the register only from one Chip, and de-asserts the chip select well in advance, before the second chip is done with erase operation, and as a result the erase operation fails. 

Our Understanding
---------------------------
On probing the FLAG STATUS REGISTER after erase operation through Oscilloscope, we found that the flag status register from Chip 1 says it is READY. But the flag status register from Chip 2 at that instant is STILL NOT READY. U-boot driver has only one status register to read, and based on that, it DESELECTS the Chip select to both chips. There is something missing in the QSPI IP controller documentation, and we don't know how to read back both status registers. Based on these findings, we modified the driver code to DESELECT Chip select based on some predefined time instead of the status register condition. After this we were able to get successful erase/write/read cycles - trade-off is that the cycles are of much longer duration. 

Code change we did to prove this
------------------------------------------------------------
drivers/mtd/spi/spi_flash.c

#define ERASE_USE_STATUS_REG_FOR_CS_DESELECT     0

	do {
		WATCHDOG_RESET();

		ret = spi_xfer(spi, 8, NULL, &status, 0);
		if (ret)
			return -1;

#if ERASE_USE_STATUS_REG_FOR_CS_DESELECT == 1
		//printf("SF: flag status register VALUE => 0x%08x \n", status);             
		if ((status & poll_bit) == check_status)
			break;
#endif

	} while (get_timer(timebase) < timeout);

The register check is commented out, and the loop completes after the timeout. 

rgds
Senthil

**Comment by sivadur** [comment]
This is known issue in Zynq QSPI controller, it reads flag status register only from the lower flash, we might have to do some workaround as you did in your case.
