### ISSUE TITLE
Can not boot from NOR flash in MicroZed

### ISSUE THREAD

**Issue by rgwan** [Xilinx/u-boot-xlnx#32]
It cannot boot from SPI-NOR Flash in MicroZed. If I enabled the CONFIG_ZYNQ_QSPI Option, it depends on CONFIG_SPL_DM option, But once I enable the CONFIG_ZYNQ_QSPI option, the SPL start fails, it shows that "### ERROR ### Please RESET the board ###"

**Comment by michalsimek** [comment]
We have discussed this issue via IRC and hopefully this problem went away.
