### ISSUE TITLE
Missing bugfix in drivers/mtd/spi/spi_flash.c

### ISSUE THREAD

**Issue by hhorst2012** [Xilinx/u-boot-xlnx#8]
There might be a missing bugfix for MODE_DUAL_STACKED in 
https://github.com/Xilinx/u-boot-xlnx/blob/master/drivers/mtd/spi/sf_ops.c#L105

Please compare the change from 
https://github.com/Xilinx/u-boot-xlnx/blob/xilinx-v14.6.01/drivers/mtd/spi/spi_flash.c#L255
to 
https://github.com/Xilinx/u-boot-xlnx/blob/xilinx-v14.7/drivers/mtd/spi/spi_flash.c#L80

**Comment by sivadur** [comment]
This now fixed. Please check latest source at
https://github.com/Xilinx/u-boot-xlnx/blob/master/drivers/mtd/spi/sf_ops.c#L283
